#!/bin/bash

# alsa_output.usb-Schiit_Audio_Modi_Multibit-00.iec958-stereo
# swapSinks=("alsa_output.pci-.*.hdmi-stereo" "alsa_output.usb-Creative_Technology_Ltd_Sound_BlasterX_G5_.*.*-stereo" "alsa_output.usb-Schiit_Audio_Modi_Multibit-.*.iec958-stereo" "alsa_output.pci-0000_0c_00.3.iec958-stereo")
#swapSinks=("alsa_output.pci-.*.hdmi-stereo" "alsa_output.pci-0000_0c_00.3.iec958-stereo" "alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.iec958-stereo")
swapSinks=("alsa_output.pci-.*.hdmi-stereo" "alsa_output.usb-Schiit_Audio_Modi_Multibit-00.analog-stereo" "alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo")
sinkNames=("HDMI"                           "Modi"                                                        "Behringer UM2")
activeSink="$(pactl list short sinks | grep "RUNNING$" | awk '{print $1}')"
activeSinkName="$(pactl list short sinks | grep "RUNNING$" | awk '{print $2}')"

echo "Active sink: ${activeSink} (${activeSinkName})"

sinkIndex=-1
for (( i=0; i<${#swapSinks[@]}; i++ )); do
    sink="${swapSinks[${i}]}"
    echo "Looking at sink: ${sink}"

    if [[ "${activeSinkName}" =~ ${sink} ]]; then
        echo "Found sink: ${sink}"
        sinkIndex=${i}
        break
    fi
done

if [[ ${sinkIndex} -eq -1 || ${sinkIndex} -eq $(( ${#swapSinks[@]} - 1 )) ]]; then
    newSinkIndex=0
else
    newSinkIndex=$(( ${sinkIndex} + 1 ))
fi

echo "Swapping to sink: ${swapSinks[${newSinkIndex}]}"

trueSinkIndex=$(pactl list short sinks | grep "${swapSinks[${newSinkIndex}]}" | awk '{print $1}')
pactl set-default-sink ${trueSinkIndex}
newlyActiveSink="$(pactl list short sinks | grep "RUNNING$" | awk '{print $1}')"
newlyActiveSinkName="$(pactl list short sinks | grep "RUNNING$" | awk '{print $2}')"

echo "New sink: ${newlyActiveSink}"

pactl set-default-sink @DEFAULT_SINK@

notify-send -i audio-card "Audio Swap" "Swapped sink from ${sinkNames[${sinkIndex}]} to ${sinkNames[${newSinkIndex}]}"
