#!/bin/bash

echo "[$(dnf repoquery --installed --qf '{"package": "%{name}", "version": "%{version}", "release": "%{release}", "arch": "%{arch}"},')]" | sed -e "s/},]/}]/"

exit 0
#!/bin/env python3


import json
import re
import subprocess

from typing import Iterable

def splitAtLastDot(value: str) -> Iterable[str]:
    parts: Iterable[str] = value.split(".")
    return [".".join(parts[0:-1]), parts[-1]]

cpl: subprocess.CompletedProcess = subprocess.run(["dnf", "list", "installed"], capture_output=True, encoding="utf-8")

line: str
pattern = re.compile(r"\s+")
values: list = []
for line in cpl.stdout.split("\n")[1:]:
    if len(line) == 0:
        continue
    parts: list = pattern.split(line)
    package: str
    arch: str
    [package, arch] = splitAtLastDot(parts[0])
    version: str
    release: str
    [version, release] = splitAtLastDot(parts[1])
    values.append({
        "arch": arch,
        "package": package,
        "release": release,
        "version": version
    })

print(json.dumps(values))
