#!/bin/bash

getafterdot()
{
    local pkg="${1}"

    echo -n "${pkg}" | sed -e "s/.\+\.//g"
}

main()
{
    local arch=""
    local package=""
    local version=""
    local release=""
    local i=0
    for part in $(dnf list installed | tail -n +2); do
        if [[ ${i} -eq 0 ]]; then
            i=1
            arch="$(getafterdot "${part}")"
            package="$(echo -n ${part} | sed -e "s/\.${arch}\$//")"
        elif [[ ${i} -eq 1 ]]; then
            i=2
            release="$(getafterdot "${part}")"
            version="$(echo -n ${part} | sed -e "s/\.${release}\$//")"
        else
            i=0
            echo "{\"arch\": \"${arch}\", \"package\": \"${package}\", \"release\": \"${release}\", \"version\": \"${version}\"}"
        fi
    done
}

main | jq -s '.'
