#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
    echo "Must be run as root."
    exit 1
fi

path="$(dirname $(readlink --canonicalize "${0}"))"
kernel="$(${path}/latestKernel)"

while [[ -n "${1}" ]]; do
    case "${1}" in
        --kernel|-k)
            kernel="${2:-${kernel}}"
            shift 2
            ;;
        --)
            shift
            break
            ;;
    esac
done

if [[ -z "${kernel}" ]]; then
    echo "Must specify new kernel to jump to!"
    exit 1;
fi

bootDir="/boot"
release="$(lsb_release -rs)"
vmlinuz="${bootDir}/vmlinuz-${kernel}.fc${release}.$(arch)"
initrd="${bootDir}/initramfs-${kernel}.fc${release}.$(arch).img"

if [[ ! -e "${vmlinuz}" || ! -e "${initrd}" ]]; then
    echo "Unable to find '${vmlinuz}' or '${initrd}'"
    exit 1
fi

cmd="$(cat /proc/cmdline | sed -e "s/vmlinuz-[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+/vmlinuz-${kernel}/")"
if [[ -f "${1}" ]]; then
    cmd="$(cat "${1}")"
    shift
fi

if [[ "${1:-}" == "+3" ]]; then
    cmd="${cmd} 3"
elif [[ "${1:-}" == "-3" ]]; then
    cmd="$(echo "${cmd}" | sed -e "s/ 3//")"
fi

kexec -l "${vmlinuz}" --initrd="${initrd}" --command-line="${cmd}" && systemctl kexec
