#!/usr/bin/env bash

TAG="$(git describe --tags --always --abbrev=0)"
VERSION="${TAG/v/}"
VERSION_PARTS=( ${VERSION//./ } )
REVISIONS=( $(git rev-list --end-of-options "${TAG}..HEAD") )
REV_COUNT=${#REVISIONS[@]}
FIX_COUNT=0
BREAKING=0

tag() {
    local NEW_VERSION="${1}"
    if [[ $(git rev-parse --verify -q --end-of-options "${NEW_VERSION}") ]]; then
        echo "Version ${NEW_VERSION} already exists! Manual tagging may be required"
        exit 1
    fi

    git tag -m "Auto-tagging ${NEW_VERSION}" "${NEW_VERSION}"
    exit 0
}

if ! git rev-parse --verify -q --end-of-options "${TAG}^{tag}" &>/dev/null; then
    echo "No tag found, attempting to auto-tag v0.0.0"
    tag "v0.0.0"
elif [[ "${REV_COUNT}" -eq 0 ]]; then
    echo "Currently sitting on latest version. No need to bump."
    exit 0
fi

for REVISION in ${REVISIONS[@]}; do
    TITLE="$(git rev-list --format="%s" -1 "${REVISION}" | tail -1)"

    if [[ "${TITLE,,}" =~ (breaking) ]]; then
        BREAKING=1
    elif [[ "${TITLE,,}" =~ (fix) ]]; then
        (( FIX_COUNT++ ))
    fi
done

if [[ "${FIX_COUNT}" -eq "${REV_COUNT}" ]]; then
    echo "Micro version bump"
    (( VERSION_PARTS[2]++ ))
elif [[ "${BREAKING}" -ge 1 ]]; then
    echo "Breaking change found, major version bump"
    (( VERSION_PARTS[0]++ ))
else
    echo "Minor version bump"
    (( VERSION_PARTS[1]++ ))
fi

IFS=. NEW_VERSION="v${VERSION_PARTS[*]}"
echo "${VERSION} -> ${NEW_VERSION}"
tag "${NEW_VERSION}"
